# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "690358425a74c07ebdf09ca2b1254176"
name = "wishlist-app"
handle = "wishlist-app-158"
application_url = "https://competitive-toronto-testing-merge.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "learning-faisal-217.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://competitive-toronto-testing-merge.trycloudflare.com/auth/callback",
  "https://competitive-toronto-testing-merge.trycloudflare.com/auth/shopify/callback",
  "https://competitive-toronto-testing-merge.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
